### PR TITLE
Update style.css

### LINKED ISSUE #1: Initialize Application
> Assigned to Tahmina

### HTML
- [x] buttons
### CSS
- [x] styling for the buttons

[TOP](#favorite-word)

---

### PR DESCRIPTION
**Pull request by tahminarasoli**
this will close #1

### CODE REVIEW

**Comment by bermarte** [comment]
Ok, but the issue is already closed.

**Comment by tahminarasoli** [comment]
> Ok, BTW the issue was already closed.

yes, I must did it before its closing. I think it is nothing much important and will not change anything in our project. you can merge it now. just to add a little style.

**Comment by bermarte** [comment]
> yes, I must did it before its closing.
No, it was already closed, but as you said it is not important; it was just to give you some extra information. (:

**Comment by bermarte** [comment]
I like the idea to style a bit the page, if you want to change the colour of the background or do something else, please do.

**Pull request merged**
